<a href="https://colab.research.google.com/github/michael-karemi/numpy-n-pandas/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
print(b.shape)

(2, 3)


In [ ]:
np.random.random((2, 3))

array([[0.86292001, 0.57069682, 0.37746215],
       [0.34259099, 0.62208804, 0.18984327]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2 ,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
c = np.array([[2.5, 8.6, 6.5], [7.5, 6.5, 9.9]])
d = np.array([[8.6, 4.8, 2.3], [5.5, 4.3, 7.7]])
print(c+d)

[[11.1 13.4  8.8]
 [13.  10.8 17.6]]


In [ ]:
print(c*d)

[[21.5  41.28 14.95]
 [41.25 27.95 76.23]]


In [ ]:
print((5*d)/c)

[[17.2         2.79069767  1.76923077]
 [ 3.66666667  3.30769231  3.88888889]]
